name: Publish Node Docker
on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: node:14

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lalitaly" --password-stdin
        docker image build -t lalitaly/nodedockergit:latest .
        docker push lalitaly/nodedockergit:latest
        
